enyo.depends(
  "../../../lib/signature_pad/signature_pad.min.js",
  "../../../lib/canvas-toBlob.js/canvas-toBlob.js",
  "core.js",
  "error.js",
  "models",
  "widgets",
  "views",
  "postbooks.js"
);
