SELECT xt.create_table('shiphead', 'public');

ALTER TABLE public.shiphead DISABLE TRIGGER ALL;

SELECT
  xt.add_column('shiphead', 'shiphead_id',               'SERIAL', 'NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_order_id',        'INTEGER', 'NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_order_type',         'TEXT', 'NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_number',             'TEXT', 'NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_shipvia',            'TEXT', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_freight',   'NUMERIC(16,4)', 'DEFAULT 0.0 NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_freight_curr_id', 'INTEGER', 'DEFAULT basecurrid() NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_notes',              'TEXT', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_shipped',         'BOOLEAN', 'DEFAULT false NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_shipdate',           'DATE', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_shipchrg_id',     'INTEGER', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_shipform_id',     'INTEGER', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_sfstatus',   'CHARACTER(1)', 'NOT NULL', 'public'),
  xt.add_column('shiphead', 'shiphead_tracknum',           'TEXT', NULL,       'public'),
  xt.add_column('shiphead', 'shiphead_dropship',        'BOOLEAN', 'NOT NULL DEFAULT FALSE', 'public');

SELECT
  xt.add_constraint('shiphead', 'shiphead_pkey', 'PRIMARY KEY (shiphead_id)', 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_number_key',
                    'UNIQUE (shiphead_number)', 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_number_check',
                    $$CHECK (shiphead_number <> '')$$, 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_order_type_check',
                    $$CHECK (shiphead_order_type IN ('SO', 'TO'))$$, 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_sfstatus_check',
                    $$CHECK (shiphead_sfstatus IN ('D',  'N', 'P'))$$, 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_freight_curr_id_fkey',
                    'FOREIGN KEY (shiphead_freight_curr_id) REFERENCES curr_symbol(curr_id)', 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_shipchrg_id_fkey',
                    'FOREIGN KEY (shiphead_shipchrg_id) REFERENCES shipchrg(shipchrg_id)', 'public'),
  xt.add_constraint('shiphead', 'shiphead_shiphead_shipform_id_fkey',
                    'FOREIGN KEY (shiphead_shipform_id) REFERENCES shipform(shipform_id)', 'public');

ALTER TABLE public.shiphead ENABLE TRIGGER ALL;

COMMENT ON TABLE shiphead IS 'General information about Shipments';

COMMENT ON COLUMN shiphead.shiphead_dropship IS 'indicates whether generated by drop-shipment';
