-- Create table
select xt.create_table('shiphead','public',TRUE)

-- Add columns
select xt.add_column('shiphead','shiphead_id','INTEGER','NOT NULL','public');
select xt.add_column('shiphead','shiphead_order_id','INTEGER','NOT NULL','public');
select xt.add_column('shiphead','shiphead_order_type','TEXT','NOT NULL','public');
select xt.add_column('shiphead','shiphead_number','TEXT','NOT NULL','public');
select xt.add_column('shiphead','shiphead_shipvia','TEXT','NULL','public');
select xt.add_column('shiphead','shiphead_freight','NUMERIC(16,4)', 'DEFAULT 0.0 NOT NULL','public');
select xt.add_column('shiphead','shiphead_freight_curr_id','INTEGER','DEFAULT basecurrid() NOT NULL','public');
select xt.add_column('shiphead','shiphead_notes','TEXT','NULL','public');
select xt.add_column('shiphead','shiphead_shipped','BOOLEAN','DEFAULT FALSE NOT NULL','public');
select xt.add_column('shiphead','shiphead_shipdate','DATE','NULL','public');
select xt.add_column('shiphead','shiphead_shipchrg_id','INTEGER','NULL','public');
select xt.add_column('shiphead','shiphead_shipform_id','INTEGER','NULL','public');
select xt.add_column('shiphead','shiphead_sfstatus','CHARACTER(1)','NOT NULL','public');
select xt.add_column('shiphead','shiphead_tracknum','TEXT','NULL','public');
select xt.add_column('shiphead','shiphead_dropship','BOOLEAN','NOT NULL DEFAULT FALSE','public','indicates whether generated by drop-shipment');

-- Add primary key
select xt.add_primary_key('shiphead','shiphead_id','public');

-- Add constraints
select xt.add_constraint('shiphead','shiphead_shiphead_number_check',$$CHECK ((shiphead_number <> ''::text))$$,'public');
select xt.add_constraint('shiphead','shiphead_shiphead_order_type_check',$$CHECK (((shiphead_order_type = 'SO'::text) OR (shiphead_order_type ='TO'::text)))$$,'public');
select xt.add_constraint('shiphead','shiphead_shiphead_sfstatus_check',$$CHECK ((((shiphead_sfstatus = 'D'::bpchar) OR (shiphead_sfstatus = 'N'::bpchar)) OR (shiphead_sfstatus = 'P'::bpchar)))$$,'public');

-- Add comment
comment on table public.shiphead is 'General information about Shipments';

-- Sequence permission
grant all on sequence public.shiphead_shiphead_id_seq TO xtrole;
