{
  "version": "1.3.9",
  "comment": "This is the time and expense schema as implemented in the Desktop client",
  "todo": "worry about the select xt.js_init();",
  "databaseScripts": [
    "te/schema/create_te_schema.sql",
    "te/functions/calcrate.sql",
    "te/functions/copyitem.sql",
    "te/functions/invoicesheets.sql",
    "te/functions/postsheet.sql",
    "te/functions/sheetstate.sql",
    "te/functions/unnest.sql",
    "te/functions/vouchersheet.sql",
    "te/trigger_functions/tehead.sql",
    "te/trigger_functions/teitem.sql",
    "te/trigger_functions/teprj.sql",
    "xt/trigger_functions/teitem_did_change.sql",
    "te/tables/tecustrate.sql",
    "te/tables/teemp.sql",
    "te/tables/teexp.sql",
    "te/tables/tehead.sql",
    "te/tables/teitem.sql",
    "te/tables/teprj.sql",
    "te/tables/teprjtask.sql",
    "xt/views/prjtaskinfo.sql",
    "xt/views/tecustrateinfo.sql",
    "xt/views/teprjinfo.sql",
    "xt/views/teprjtaskinfo.sql",
    "xt/views/teexpinfo.sql",
    "xt/views/teheadinfo.sql",
    "xm/javascript/worksheet.sql",
    "priv.sql",
    "register.sql"
  ]
}
