{
  "name": "inventory_foundation_frozen",
  "version": "4.4.0",
  "comment": "Inventory foundation",
  "loadOrder": 44,
  "databaseScripts": [
    "frozen/initUpgrade.sql",
    "frozen/misc/backupanddroptable.sql",
    "frozen/tables/bomhist.sql",
    "frozen/tables/gltranssync.sql",
    "frozen/tables/itemlocrsrv.sql",
    "frozen/tables/ls.sql",
    "frozen/tables/lsdetail.sql",
    "frozen/tables/regtype.sql",
    "frozen/tables/lsreg.sql",
    "frozen/tables/lsseq.sql",
    "frozen/tables/lswarr.sql",
    "frozen/tables/mpsmrpwork.sql",
    "frozen/tables/planord.sql",
    "frozen/tables/planreq.sql",
    "frozen/tables/rahead.sql",
    "frozen/tables/rahist.sql",
    "frozen/tables/raitem.sql",
    "frozen/tables/raitemls.sql",
    "frozen/tables/rev.sql",
    "frozen/tables/shipitemlocrsrv.sql",
    "frozen/tables/shipitemrsrv.sql",
    "frozen/tables/createreserve.sql",
    "frozen/tables/tohead.sql",
    "frozen/tables/toheadtax.sql",
    "frozen/tables/toitem.sql",
    "frozen/tables/toitemtax.sql",
    "frozen/tables/trialbalsync.sql",
    "frozen/tables/usrsite.sql",
    "frozen/tables/lsindex.sql",
    "frozen/misc/add_fks_to_postbooks.sql",
    "frozen/misc/alteritemtrans.sql",
    "frozen/misc/insertprivs.sql",
    "frozen/misc/lsreg_number_seq.sql",
    "frozen/misc/dropbackupanddroptable.sql",
    "frozen/misc/updateMetric.sql",
    "frozen/empty_data.sql"
  ]
}
