enyo.depends(
  "assignment_box.js",
  "comment_box.js",
  "documents_box.js",
  "grid_box.js",
  "list.js",
  "list_box.js",
  "list_relations.js",
  "list_relations_box.js",
  "list_relations_editor_box.js",
  "transaction_list.js",
  "transaction_list_container.js",
  "workspace.js"
);
