{
  "name": "quality",
  "version": "1.0.0",
  "comment": "Quality Control",
  "loadOrder": 120,
  "dependencies": ["manufacturing"],
  "defaultSchema": "xt",
  "databaseScripts": [
    "../../foundation-database/source/xm/javascript/quality.sql",
    "../../foundation-database/source/xt/tables/qspec.sql",
    "../../foundation-database/source/xt/tables/qspectype.sql",
    "../../foundation-database/source/xt/tables/qphead.sql",
    "../../foundation-database/source/xt/tables/qpitem.sql",
    "../../foundation-database/source/xt/tables/qpheadass.sql",
    "../../foundation-database/source/xt/tables/qthead.sql",
    "../../foundation-database/source/xt/tables/qtitem.sql",
    "../../foundation-database/source/xt/tables/qtrlscode.sql",
    "../../foundation-database/source/xt/tables/qtrsncode.sql",
    "../../foundation-database/source/xt/tables/qplanemlprofile.sql",
    "../../foundation-database/source/xt/tables/qualitytestwf.sql",
    "../../foundation-database/source/xt/tables/qualityplanwf.sql",
    "../../foundation-database/source/xt/tables/acttype.sql",
    "../../foundation-database/source/xt/tables/rptdef.sql",
    "../../foundation-database/source/xt/trigger_functions/qphead_trigger.sql",
    "../../foundation-database/source/xt/trigger_functions/qthead_trigger.sql",
    "../../foundation-database/source/xt/trigger_functions/qtitem_trigger.sql",
    "../../foundation-database/source/xt/trigger_functions/inv_hist_did_change.sql",
    "../../foundation-database/source/xt/trigger_functions/inv_detail_did_change.sql",
    "../../foundation-database/source/xt/trigger_functions/triggerwooperquality.sql",
    "../../foundation-database/source/public/tables/invhist.sql",
    "../../foundation-database/source/public/tables/invdetail.sql",
    "../../foundation-database/source/public/tables/wooper.sql",
    "../../foundation-database/source/xt/functions/quality_comment_type.sql",
    "../../foundation-database/source/xt/functions/formatqualityitemnumber.sql",
    "../../foundation-database/source/xt/functions/wftype.sql",
    "../../foundation-database/source/priv.sql",
    "../../foundation-database/source/xt/tables/pkgmetasql/qualityTests-detail.mql",
    "../../foundation-database/source/xt/tables/pkgmetasql/qualityTests-summary.mql",
    "../../foundation-database/source/xt/tables/pkgscript/initMenu.js",
    "../../foundation-database/source/xt/tables/pkgscript/qualityTests.js",
    "../../foundation-database/source/xt/tables/pkgreport/QualityCertificate.xml",
    "../../foundation-database/source/xt/tables/pkgreport/QualityNonConformance.xml",
    "../../foundation-database/source/xt/tables/pkgreport/QualityTest.xml",
    "../../foundation-database/source/xt/tables/pkgreport/QualityTestSummary.xml",
    "../../foundation-database/source/xt/tables/pkgreport/WorkOrderQualityCertificate.xml",
    "../../foundation-database/metasql/qpheadass-detail.mql",
    "../../foundation-database/metasql/qplan-detail.mql",
    "../../foundation-database/metasql/qspec-detail.mql",
    "../../foundation-database/metasql/qtest-detail.mql",
    "../../foundation-database/metasql/qtitem-detail.mql",
    "../../foundation-database/scripts/qplan.js",
    "../../foundation-database/scripts/qplanass.js",
    "../../foundation-database/scripts/qplans.js",
    "../../foundation-database/scripts/qreasoncode.js",
    "../../foundation-database/scripts/qreasoncodes.js",
    "../../foundation-database/scripts/qreleasecode.js",
    "../../foundation-database/scripts/qreleasecodes.js",
    "../../foundation-database/scripts/qspec.js",
    "../../foundation-database/scripts/qspecs.js",
    "../../foundation-database/scripts/qspectype.js",
    "../../foundation-database/scripts/qspectypes.js",
    "../../foundation-database/scripts/qtest.js",
    "../../foundation-database/scripts/qtests.js",
    "../../foundation-database/scripts/qtitem.js",
    "../../foundation-database/scripts/setup.js",
    "../../foundation-database/sql/qthead_doctype.sql",
    "../../foundation-database/uiforms/qplan.ui",
    "../../foundation-database/uiforms/qplanass.ui",
    "../../foundation-database/uiforms/qreasoncode.ui",
    "../../foundation-database/uiforms/qreasoncodes.ui",
    "../../foundation-database/uiforms/qreleasecode.ui",
    "../../foundation-database/uiforms/qreleasecodes.ui",
    "../../foundation-database/uiforms/qspec.ui",
    "../../foundation-database/uiforms/qspectype.ui",
    "../../foundation-database/uiforms/qspectypes.ui",
    "../../foundation-database/uiforms/qtconfig.ui",
    "../../foundation-database/uiforms/qtest.ui",
    "../../foundation-database/uiforms/qtitem.ui"
  ],
  "routes": [
    {
      "path": "quality",
      "verb": "no-route",
      "filename": "routes/rpttransforms.js",
      "functionName": "qualityTransformFunctions"
    }
  ]    
}
