module.exports = [
// Known Item Site (need for the uuid)
{"nameSpace":"XM","type":"ItemSite","id":"4e89cbf0-c36d-4103-e29c-625439df8b4f","data":{"isActive":true,"soldRanking":1,"isPurchased":false,"abcClass":"A","isAutomaticAbcClassUpdates":false,"isDropShip":false,"costMethod":"S","cycleCountFrequency":0,"isStocked":false,"safetyStock":0,"useParameters":false,"useParametersManual":false,"reorderLevel":0,"orderToQuantity":0,"minimumOrderQuantity":0,"multipleOrderQuantity":0,"maximumOrderQuantity":0,"isLocationControl":false,"isReceiveLocationAuto":false,"isIssueLocationAuto":false,"isCreatePurchaseOrdersForSalesOrders":false,"isCreatePurchaseRequestsForSalesOrders":false,"isManufactured":false,"isCreatePurchaseRequestsForWorkOrders":false,"isCreateWorkOrdersForSalesOrders":false,"item":"BPAINT1","site":"WH2","plannerCode":"NONE","costCategory":"FINISHED","comments":[],"receiveLocation":null,"stockLocation":null,"issueLocation":null,"traceSequence":null,"supplySite":null,"restrictedLocationsAllowed":[],"uuid":"4e89cbf0-c36d-4103-e29c-625439df8b4f","controlMethod":"R","isSold":true,"notes":"Demo Item Site"},"binaryField":null,"requery":false,"encoding":"rjson"},

// Set Quality Test Number
{"nameSpace":"XM","type":"Quality","dispatch":{"functionName":"commitSettings","parameters":[[{"op":"replace","path":"/NextQualityTestNumber","value":55000},{"op":"replace","path":"/QTNumberGeneration","value":"A"}]]},"encoding":"rjson"},

// Quality Email Profiles
{"nameSpace":"XM","type":"QualityPlanEmailProfile","id":"TESTER1","data":{"name":"TESTER1","description":"Tester User","from":"quality@xtuple.com","replyTo":"","to":"tester@xtuple.com","cc":"","bcc":"","subject":"A Quality Test has been generated","body":"A Quality Test has been generated"},"binaryField":null,"requery":false,"encoding":"rjson"},

{"nameSpace":"XM","type":"QualityPlanEmailProfile","id":"SUPERV","data":{"name":"SUPERV","description":"Test Supervisor","from":"quality@xtuple.com","replyTo":"","to":"SUPERV@xtuple.com","cc":"","bcc":"","subject":"Quality Test initiated ","body":"A new Quality Test has been initiated."},"binaryField":null,"requery":false,"encoding":"rjson"},

{"nameSpace":"XM","type":"QualityPlanEmailProfile","id":"TESTER2","data":{"name":"TESTER2","description":"Tester2","from":"quality@xtuple.com","replyTo":"","to":"tester@xtuple.com","cc":"","bcc":"","subject":"Quality Test Initiated ","body":"A new Quality Test has been initiated."},"binaryField":null,"requery":false,"encoding":"rjson"},

// Quality Specifications
{"nameSpace":"XM","type":"QualitySpecification","id":"QS300-1","uuid":"34029ea7-d09f-41d9-c32a-f41643b7beb1","data":{"code":"QS300-1","description":"Colour Match","testType":"B","target":null,"upper":null,"lower":null,"testUnit":null,"instructions":"Visual comparison with colour swatch XX-567-AB"},"binaryField":null,"requery":false,"encoding":"rjson"},
{"nameSpace":"XM","type":"QualitySpecification","id":"QS300-2","uuid":"34029ea7-d09f-41d9-c32a-f41643b7beb2", "data":{"code":"QS300-2","description":"Temperature 75","testType":"N","target":75,"upper":76.5,"lower":74.5,"testUnit":"C","instructions":"Measure temperature for 15 seconds."},"binaryField":null,"requery":false,"encoding":"rjson"},
{"nameSpace":"XM","type":"QualitySpecification","id":"QS300-3","uuid":"35029ea7-d09f-41d9-c32a-f41643b7beb2", "data":{"code":"QS300-3","description":"Width 50.5mm","testType":"N","target":50.5,"upper":52.5,"lower":49.5,"testUnit":"MM","instructions":"Measure width from point A to B"},"binaryField":null,"requery":false,"encoding":"rjson"},
{"nameSpace":"XM","type":"QualitySpecification","id":"QS300-4","uuid":"36029ea7-d09f-41d9-c32a-f41643b7beb2", "data":{"code":"QS300-4","description":"Height 1025mm","testType":"N","target":1025,"upper":1030,"lower":1020,"testUnit":"MM","instructions":"Measure height of unit from point C to D"},"binaryField":null,"requery":false,"encoding":"rjson"},
{"nameSpace":"XM","type":"QualitySpecification","id":"QS500-1","data":{"code":"QS500-1","description":"Visual Inspection","testType":"B","instructions":"Visual check for defects"},"binaryField":null,"requery":false,"encoding":"rjson"},

// Quality Plans
{"nameSpace":"XM","type":"QualityPlan","id":"QP-300-1","data":{"revisionStatus":"A","emailProfile":"SUPERV","items":[{"specification":"QS300-1","uuid":"34029ea7-d09f-41d9-c32a-f41643b7beb1"}, {"specification":"QS300-2","uuid":"34029ea7-d09f-41d9-c32a-f41643b7beb2"}],"itemSiteAssignment":[{"frequency_type":"A","item":"BTRUCK1","site":"WH2","uuid":"24b258f9-84e5-4d19ef33-4d924c4b65d6","production":true}],"workflow":[{"status":"P","startSet":false,"startOffset":0,"dueSet":false,"dueOffset":0,"priority":"Normal","sequence":0,"owner":null,"assignedTo":null,"uuid":"b29d6602-2486-47f5-b681-3b7bd2b187d2","name":"Scrap","description":"Scrap Item","workflowType":"S","completedParentStatus":"S","deferredParentStatus":"S"},{"status":"I","startSet":true,"startOffset":0,"dueSet":true,"dueOffset":1,"priority":"Normal","sequence":0,"owner":null,"assignedTo":null,"uuid":"d6734789-0495-45c1-9cd3-f9db134573e0","name":"Test","description":"Temperature Test","workflowType":"I","completedParentStatus":"OK","deferredParentStatus":"S","deferredSuccessors":"b29d6602-2486-47f5-b681-3b7bd2b187d2"}],"comments":[],"code":"QP-300-1","description":"Pasteurisation Temperature","revisionNumber":"1","revisionDate":"2014-05-15T00:00:00.000Z","notes":"Sample Quality Plan #2"},"binaryField":null,"requery":false,"encoding":"rjson"},

// Quality Test
{"nameSpace":"XM","type":"QualityTest","id":"4b5d05bc-f3a0-44d4-c611-e01db888442d","data":{"testStatus":"O","testDisposition":"I","qualityPlan":"QP-300-1","item":"BTRUCK1","site":"WH1","orderType":"WO","orderNumber":"10083","trace":null,"qualityTestItems":[{"qualityPlanItem":"34029ea7-d09f-41d9-c32a-f41643b7beb2","description":"Temperature 72","instructions":"Measure temperature for 15 seconds.","target":72,"upper":75,"lower":72,"testUnit":"C","testType":"N","result":"O","lineNumber":1,"uuid":"4e10719a-cbea-4e02-da8b-5d3c90e7fb98"}],"workflow":[{"owner":"admin","assignedTo":"admin","status":"P","priority":"Normal","sequence":0,"uuid":"e4ca1a3a-8ea1-479d-e7b5-4806251f2695","name":"Rework","description":"Rework this Item","workflowType":"R","notes":null,"completedParentStatus":"R","deferredParentStatus":"R","completedSuccessors":null,"deferredSuccessors":null},{"owner":"admin","assignedTo":"admin","status":"I","priority":"Normal","sequence":0,"uuid":"c27229fa-6ce6-424a-870f-a5ab06ec0862","name":"Test","description":"Temperature Test","workflowType":"I","startDate":"2014-05-26T12:00:00.000Z","dueDate":"2014-05-27T12:00:00.000Z","notes":null,"completedParentStatus":"OK","deferredParentStatus":"S","completedSuccessors":null,"deferredSuccessors":"e4ca1a3a-8ea1-479d-e7b5-4806251f2695"}],"comments":[],"uuid":"4b5d05bc-f3a0-44d4-c611-e01db888442d","number":"10003","revisionNumber":"1","startDate":"2014-05-26T12:00:00.000Z","completedDate":null,"testNotes":"Initial test"},"binaryField":null,"requery":false,"encoding":"rjson"},

// Create Lot/Serial Test Items
{"nameSpace":"XM","type":"Item","id":"SERIAL1","data":{"description1":"Serial Enabled Item","description2":"","isActive":true,"isFractional":false,"isSold":true,"itemType":"P","listPrice":50,"isExclusive":false,"isPicklist":false,"classCode":"TOYS-CARS","inventoryUnit":"EA","productCategory":"CLASSIC-METAL","freightClass":null,"priceUnit":"EA","aliases":[],"comments":[],"characteristics":[],"accounts":[],"contacts":[],"items":[],"files":[],"urls":[],"itemSites":[],"customers":[],"number":"SERIAL1","wholesalePrice":50},"binaryField":null,"encoding":"rjson"},

{"nameSpace":"XM","type":"ItemSite","id":"22614f35-9755-4c68-eb71-2746685fb0c7","data":{"isActive":true,"soldRanking":1,"isPurchased":true,"abcClass":"A","isAutomaticAbcClassUpdates":false,"isDropShip":false,"costMethod":"S","cycleCountFrequency":0,"isStocked":false,"safetyStock":0,"useParameters":false,"useParametersManual":false,"reorderLevel":0,"orderToQuantity":0,"minimumOrderQuantity":0,"multipleOrderQuantity":0,"maximumOrderQuantity":0,"isLocationControl":false,"isReceiveLocationAuto":false,"isIssueLocationAuto":false,"isCreatePurchaseOrdersForSalesOrders":false,"isCreatePurchaseRequestsForSalesOrders":false,"isManufactured":false,"isCreatePurchaseRequestsForWorkOrders":false,"isCreateWorkOrdersForSalesOrders":false,"item":"SERIAL1","site":"WH1","plannerCode":"MRP","costCategory":"FINISHED","comments":[],"receiveLocation":null,"stockLocation":null,"issueLocation":null,"traceSequence": "SERIAL","restrictedLocationsAllowed":[],"uuid":"22614f35-9755-4c68-eb71-2746685fb0c7","planningSystem":"N","isPlannedTransferOrders":false,"supplySite":null,"controlMethod":"S","isSold":true},"binaryField":null,"requery":false,"encoding":"rjson"},

{"nameSpace":"XM","type":"Item","id":"LOT1","data":{"description1":"Lot Enabled Item","description2":"Purple Truck","isActive":true,"isFractional":false,"isSold":true,"itemType":"P","listPrice":50,"isExclusive":false,"isPicklist":false,"classCode":"TOYS-CARS","inventoryUnit":"EA","productCategory":"CLASSIC-METAL","freightClass":null,"priceUnit":"EA","aliases":[],"comments":[],"characteristics":[],"accounts":[],"contacts":[],"items":[],"files":[],"urls":[],"itemSites":[],"customers":[],"number":"LOT1","wholesalePrice":50},"binaryField":null,"encoding":"rjson"},

{"nameSpace":"XM","type":"ItemSite","id":"23614f35-9755-4c68-eb71-2746685fc0c7","data":{"isActive":true,"soldRanking":1,"isPurchased":true,"abcClass":"A","isAutomaticAbcClassUpdates":false,"isDropShip":false,"costMethod":"S","cycleCountFrequency":0,"isStocked":false,"safetyStock":0,"useParameters":false,"useParametersManual":false,"reorderLevel":0,"orderToQuantity":0,"minimumOrderQuantity":0,"multipleOrderQuantity":0,"maximumOrderQuantity":0,"isLocationControl":false,"isReceiveLocationAuto":false,"isIssueLocationAuto":false,"isCreatePurchaseOrdersForSalesOrders":false,"isCreatePurchaseRequestsForSalesOrders":false,"isManufactured":false,"isCreatePurchaseRequestsForWorkOrders":false,"isCreateWorkOrdersForSalesOrders":false,"item":"LOT1","site":"WH1","plannerCode":"MRP","costCategory":"FINISHED","comments":[],"receiveLocation":null,"stockLocation":null,"issueLocation":null,"traceSequence": "LOT","restrictedLocationsAllowed":[],"uuid":"23614f35-9755-4c68-eb71-2746685fc0c7","planningSystem":"N","isPlannedTransferOrders":false,"supplySite":null,"controlMethod":"L","isSold":true},"binaryField":null,"requery":false,"encoding":"rjson"},

];
