/*jshint node:true, indent:2, curly:false, eqeqeq:true, immed:true,
latedef:true, newcap:true, noarg:true, regexp:true, undef:true,
strict:true, trailing:true, white:true */
/*global XT:true */

(function () {
  "use strict";

  var lang = XT.stringsFor("en_US", {
    "_actualOpportunities": "Actual Opportunities",
    "_accountRep": "Account Rep",
    "_allBookings": "All Bookings",
    "_allOpportunities": "All Opportunities",
    "_allQuotes": "All Quotes",
    "_amount": "Amount",
    "_amountBooking": "Amount, Booking",
    "_amountBookingDiscount": "Amount, Booking Discount",
    "_amountCost": "Amount, Cost",
    "_amountOpportunity": "Amount, Opportunity",
    "_amountOpportunityForecast": "Amount, Opportunity Forecast",
    "_amountOpportunityForecastWeighted": "Amount, Opportunity Forecast Weighted",
    "_amountOpportunityWeighted": "Amount, Opportunity Weighted",
    "_amountProfit": "Amount: Profit",
    "_amountQuote": "Amount: Quote",
    "_amountQuoteDiscount": "Amount: Quote Discount",
    "_amountShipment": "Amount: Shipment",
    "_amountShipmentDiscount": "Amount: Shipment Discount",
    "_areaChart": "Area Chart",
    "_assignedOpportunities": "Assigned Opportunities",
    "_average": "Average",
    "_averageBooking": "Average, Booking",
    "_averageOpportunity": "Average, Opportunity",
    "_averageOpportunityWeighted": "Average, Opportunity Weighted",
    "_averageQuote": "Average, Quote",
    "_backlogTrailing": "Backlog",
    "_balanceBacklog": "Balance, Backlog",
    "_barChart": "Bar Chart",
    "_billRegion": "Billing Region",
    "_booking": "Booking",
    "_bookingsTrailing": "Sales Orders",
    "_bubbleChart": "Bubble Chart",
    "_chartType": "Chart Type",
    "_convertedQuotes": "Converted Quotes",
    "_count": "Count",
    "_countBookings": "Count, Bookings",
    "_countOpportunities": "Count, Opportunities",
    "_countQuotes": "Count, Quotes",
    "_countShipments": "Count, Shipments",
    "_crmAccount": "Account",
    "_daysBookingToShipment": "Days, Booking to Shipment",
    "_daysStartToActual": "Days, Start to Actual",
    "_daysStartToAssigned": "Days, Start to Assigned",
    "_daysStartToTarget": "Days, Start to Target",
    "_dimension": "Dimension",
    "_ending": " ending ",
    "_interestB2SImpact": "Interest, B2S Impact",
    "_lineChart": "Line Chart",
    "_measure": "Measure",
    "_measureName": "Measure Name",
    "_opportunity": "Opportunity",
    "_opportunitiesActiveNext": "Opportunities, next 6 months",
    "_opportunityForecastTrailing": "Opportunity Forecast",
    "_opportunitiesFunnel": "Opportunity Pipeline",
    "_opportunityQuoteBookingFunnel": "Sales Pipeline",
    "_opportunitiesTrailing": "Opportunities",
    "_opportunitiesBookingsTrailing": "Opportunities-Sales",
    "_percentForecastProbability": "Percentage, Forecast Probability",
    "_percentageMargin": "Percentage, Margin",
    "_percentProbabilityOpportunity": "Percentage, Probability Opportunity",
    "_periodEnding": "Period Ending",
    "_previousYear": "Previous Year",
    "_product": "Item",
    "_productCategory": "Item Category",
    "_productClass": "Item Class",
    "_productType": "Item Type",
    "_quotesTrailing": "Quotes",
    "_quotesActiveTrailing": "Active Quotes",
    "_ratioConversion": "Ratio, Conversion",
    "_ratioConversionWeighted": "Ratio, Conversion Weighted",
    "_salesVelocity": "Sales Velocity",
    "_shipment": "Shipment",
    "_shipmentsTrailing": "Shipments, Profit",
    "_shipRegion": "Shipping Region",
    "_targetedOpportunities": "Targeted Opportunities",
    "_toplistTrailingBacklog": "Backlog Top List",
    "_toplistTrailingBooking": "Sales Top List",
    "_toplistTrailingOpportunity": "Opportunities Top List",
    "_toplistTrailingOpportunityActive": "Active Opportunities Top List",
    "_toplistTrailingQuote": "Quotes Top List",
    "_toplistTrailingQuoteActive": "Active Quotes Top List",
    "_toplistTrailingShipments": "Shipments, Profit Top List",
    "_wonOpportunities": "Opportunities Won"
  });

  if (typeof exports !== 'undefined') {
    exports.language = lang;
  }
}());
