/*jshint node:true, indent:2, curly:false, eqeqeq:true, immed:true,
latedef:true, newcap:true, noarg:true, regexp:true, undef:true,
strict:true, trailing:true, white:true */
/*global XT:true */

(function () {
  "use strict";

  var lang = XT.stringsFor("en_US", {
    "_actualOpportunities": "Actual Opportunities",
    "_account": "Account",
    "_active": "Active ",
    "_allBookings": "All Bookings",
    "_allOpportunities": "All Opportunities",
    "_allQuotes": "All Quotes",
    "_amount": "Amount",
    "_amountBooking": "Booking Amount",
    "_amountBookingDiscount": "Booking Discount",
    "_amountCost": "Shipment Cost",
    "_amountOpportunity": "Opportunity Amount",
    "_amountOpportunityForecast": "Opportunity Forecast",
    "_amountOpportunityForecastWeighted": "Opportunity Forecast Weighted",
    "_amountOpportunityWeighted": "Opportunity Weighted",
    "_amountProfit": "Shipment Profit",
    "_amountQuote": "Quote Amount",
    "_amountQuoteDiscount": "Quote Discount",
    "_amountShipment": "Shipment Amount",
    "_amountShipmentDiscount": "Shipment Discount",
    "_areaChart": "Area Chart",
    "_assignedOpportunities": "Assigned Opportunities",
    "_average": "Average",
    "_averageBooking": "Booking Average",
    "_averageOpportunity": "Opportunity  Average",
    "_averageOpportunityWeighted": "Opportunity Weighted  Average",
    "_averageQuote": "Quote Average",
    "_backlogTrailing": "Backlog",
    "_balanceBacklog": "Backlog Balance",
    "_barChart": "Bar Chart",
    "_billRegion": "Billing Region",
    "_booking": "Booking",
    "_bookingsTrailing": "Sales Orders",
    "_bubbleChart": "Bubble Chart",
    "_chartFilters": "Chart Filters",
    "_chartType": "Chart Type",
    "_classCode": "Item Class",  // really itemClass
    "_chooseDimensionMeasure": "Choose Dimension and Measure",
    "_chooseMeasure": "Choose Measure",
    "_convertedQuotes": "Converted Quotes",
    "_count": "Count",
    "_countBacklog": "Backlog Booking Count",
    "_countBookings": "Booking Count",
    "_countForecastOpportunities": "Opportunity Forecast Count",
    "_countOpportunities": "Opportunity Count",
    "_countQuotes": "Quote Count",
    "_countShipments": "Shipment Count",
    "_current": "Current",
    "_daysBookingToShipment": "Booking to Shipment Days",
    "_daysStartToActual": "Opportunity Start to Actual",
    "_daysStartToAssigned": "Opportunity Start to Assigned",
    "_daysStartToTarget": "Opportunity Start to Target",
    "_dimension": "Dimension",
    "_ending": " ending ",
    "_endPeriod": "Ending Period",
    "_interestB2SImpact": "Backlog Impact",
    "_item": "Item",
    "_itemType": "Item Type",
    "_lineChart": "Line Chart",
    "_measure": "Measure",
    "_measureName": "Measure Name",
    "_month": "Month",
    "_next6Months": "Next 6 Months",
    "_opportunity": "Opportunity",
    "_opportunitiesActiveNext": "Opportunities Next 6 months",
    "_opportunityForecastTrailing": "Opportunity Forecast",
    "_opportunitiesFunnel": "Opportunity Pipeline",
    "_opportunityQuoteBookingFunnel": "Sales Pipeline",
    "_opportunitiesTrailing": "Opportunities",
    "_opportunitiesBookingsTrailing": "Opportunity Conversion",
    "_percentForecastProbability": "Forecast Probability",
    "_percentOpportunityForecastProbability": "Opportunity Forecast Probability",
    "_percentageMargin": "Shipment Margin",
    "_percentProbabilityOpportunity": "Opportunity Probability",
    "_periodEnding": "Period Ending",
    "_previousYear": "Previous Year",
    "_productCategory": "Item Category",  // really itemCategory
    "_quotesTrailing": "Quotes",
    "_quotesActiveTrailing": "Active Quotes",
    "_ratioConversion": "Opportunity Conversion Ratio",
    "_ratioConversionWeighted": "Opporunity Conversion Weighted Ratio",
    "_salesRep": "Sales Rep",
    "_salesVelocity": "Sales Velocity",
    "_shipment": "Shipment",
    "_shipmentsTrailing": "Shipments-Profit",
    "_shipRegion": "Shipping Region",
    "_targetedOpportunities": "Targeted Opportunities",
    "_toplistTrailing12": "Top List Trailing 12",
    "_toplistTrailingBacklog": "Backlog Top List",
    "_toplistTrailingBooking": "Sales Top List",
    "_toplistTrailingOpportunity": "Opportunities Top List",
    "_toplistTrailingOpportunityActive": "Active Opportunities Top List",
    "_toplistTrailingQuote": "Quotes Top List",
    "_toplistTrailingQuoteActive": "Active Quotes Top List",
    "_toplistTrailingShipments": "Shipments, Profit Top List",
    "_trailing12": " Trailing 12",
    "_wonOpportunities": "Opportunities Won",
    "_year": "Year"
  });

  if (typeof exports !== 'undefined') {
    exports.language = lang;
  }
}());
