enyo.depends(
  "bill_of_material.js",
	"configure.js",
  "inventory.js",
  "item.js",
  "item_site.js",
  "order.js",
  "planned_order.js",
  "routing.js",
  "sales_order.js",
  "work_order.js",
  "manufacturing.js",
  "static.js",
  "startup.js"
);
