enyo.depends(
  "dimple/lib/d3.v3.min.js",
  "dimple/dist/dimple.v1.1.1.js",
  "RGraph/libraries/RGraph.common.core.js",
  "RGraph/libraries/RGraph.funnel.js",
  "RGraph/libraries/RGraph.common.tooltips.js",
  "RGraph/libraries/RGraph.common.dynamic.js",
  "leaflet/dist/leaflet.css",
  "leaflet/dist/leaflet-8dev.js",
  "leaflet-markercluster/dist/leaflet.markercluster-src.js",
  "leaflet-markercluster/dist/MarkerCluster.css"
);
