enyo.depends(
  "bi_chart.js",
  "bi_chart_dim_measure.js",
  "bi_chart_type_measure.js",
  "bi_chart_measure.js",
  "bi_chart_nopicker.js",
  "bi_comparetimesum_chart.js",
  "bi_funnel_chart.js",
  "bi_timeseries_chart.js",
  "bi_toplist_chart.js",
  "crm_funnel_chart.js",
  "crm_timeseries_chart.js",
  "crm_toplist_chart.js",
  "list.js",
  "parameter.js",
  "sales_toplist_chart.js",
  "sales_timeseries_chart.js"
);