FORMS += ../pkguiform/bbom.ui \
         ../pkguiform/bbomItem.ui \
         ../pkguiform/bboms.ui \
         ../pkguiform/bomItemAddend.ui \
         ../pkguiform/bomitems.ui \
         ../pkguiform/boo.ui \
         ../pkguiform/booItem.ui \
         ../pkguiform/booItemList.ui \
         ../pkguiform/booList.ui \
         ../pkguiform/booitemImage.ui \
         ../pkguiform/changeQtyToDistributeFromBreeder.ui \
         ../pkguiform/configurePDAddend.ui \
         ../pkguiform/configureTimeAddend.ui    \
         ../pkguiform/configureWOAddend.ui \
         ../pkguiform/copyBOO.ui \
         ../pkguiform/copyItemBOO.ui    \
         ../pkguiform/copyPlannedSchedule.ui \
         ../pkguiform/correctOperationsPosting.ui \
         ../pkguiform/createBufferStatusByItem.ui \
         ../pkguiform/createBufferStatusByPlannerCode.ui \
         ../pkguiform/distributeBreederProduction.ui \
         ../pkguiform/dspBreederDistributionVariance.ui \
         ../pkguiform/dspCapacityBufferStatusByWorkCenter.ui \
         ../pkguiform/dspInventoryBufferStatusByParameterList.ui \
         ../pkguiform/dspLaborVarianceByBOOItem.ui \
         ../pkguiform/dspMPSDetail.ui \
         ../pkguiform/dspMRPException.ui \
         ../pkguiform/dspOperationsByWorkCenter.ui \
         ../pkguiform/dspPlannedRevenueExpensesByPlannerCode.ui \
         ../pkguiform/dspPoItemsByBufferStatus.ui \
         ../pkguiform/dspRoughCutByWorkCenter.ui \
         ../pkguiform/dspSequencedBOM.ui \
         ../pkguiform/dspStandardOperationsByWorkCenter.ui \
         ../pkguiform/dspTimePhasedAvailableCapacityByWorkCenter.ui \
         ../pkguiform/dspTimePhasedCapacityByWorkCenter.ui \
         ../pkguiform/dspTimePhasedDemandByPlannerCode.ui \
         ../pkguiform/dspTimePhasedLoadByWorkCenter.ui \
         ../pkguiform/dspTimePhasedPlannedREByPlannerCode.ui \
         ../pkguiform/dspTimePhasedProductionByItem.ui \
         ../pkguiform/dspTimePhasedProductionByPlannerCode.ui \
         ../pkguiform/dspTimePhasedRoughCutByWorkCenter.ui \
         ../pkguiform/dspWoBufferStatusByParameterList.ui \
         ../pkguiform/dspWoEffortByUser.ui \
         ../pkguiform/dspWoEffortByWorkOrder.ui \
         ../pkguiform/dspWoOperationBufrStsByWorkCenter.ui \
         ../pkguiform/dspWoOperationsByWorkCenter.ui \
         ../pkguiform/dspWoOperationsByWorkOrder.ui \
         ../pkguiform/itemsiteSched.ui \
         ../pkguiform/laborRate.ui \
         ../pkguiform/laborRates.ui \
         ../pkguiform/ltanalysis.ui \
         ../pkguiform/operationType.ui  \
         ../pkguiform/operationTypes.ui \
         ../pkguiform/plannedSchedule.ui \
         ../pkguiform/plannedScheduleItem.ui \
         ../pkguiform/plannedSchedules.ui \
         ../pkguiform/poReleaseHist.ui  \
         ../pkguiform/postOperations.ui \
         ../pkguiform/printProductionEntrySheet.ui \
         ../pkguiform/printWoRouting.ui \
         ../pkguiform/runMPSByPlannerCode.ui \
         ../pkguiform/runMRPException.ui \
         ../pkguiform/shift.ui \
         ../pkguiform/shifts.ui \
         ../pkguiform/standardOperation.ui \
         ../pkguiform/standardOperations.ui \
         ../pkguiform/whseCalendar.ui \
         ../pkguiform/whseCalendars.ui \
         ../pkguiform/whseWeek.ui \
         ../pkguiform/woMaterialItemAddend.ui \
         ../pkguiform/woOperation.ui \
         ../pkguiform/woTimeClock.ui
         ../pkguiform/wooItemList.ui \
         ../pkguiform/workCenter.ui \
         ../pkguiform/workCenters.ui \
         ../pkguiform/workOrderOperations.ui \
         ../pkguiform/wotc.ui \

SOURCES = ../pkgscript/databaseInformation.js \
          ../pkgscript/ParameterGroupUtils.js \
          ../pkgscript/bbom.js \
          ../pkgscript/bbomItem.js \
          ../pkgscript/bboms.js \
          ../pkgscript/bomItem.js \
          ../pkgscript/bomitems.js \
          ../pkgscript/boo.js \
          ../pkgscript/booItem.js \
          ../pkgscript/booItemList.js \
          ../pkgscript/booList.js \
          ../pkgscript/booitemImage.js \
          ../pkgscript/changeQtyToDistributeFromBreeder.js \
          ../pkgscript/closeWo.js \
          ../pkgscript/configureMS.js \
          ../pkgscript/configurePD.js \
          ../pkgscript/configureWO.js \
          ../pkgscript/copyBOO.js \
          ../pkgscript/copyItem.js \
          ../pkgscript/copyPlannedSchedule.js \
          ../pkgscript/correctOperationsPosting.js \
          ../pkgscript/correctProductionPosting.js \
          ../pkgscript/costCategory.js \
          ../pkgscript/createBufferStatusByItem.js \
          ../pkgscript/createBufferStatusByPlannerCode.js \
          ../pkgscript/createItemSitesByClassCode.js \
          ../pkgscript/createPlannedOrdersByItem.js \
          ../pkgscript/createPlannedOrdersByPlannerCode.js \
          ../pkgscript/distributeBreederProduction.js \
          ../pkgscript/dspBreederDistributionVariance.js \
          ../pkgscript/dspCapacityBufferStatusByWorkCenter.js \
          ../pkgscript/dspInventoryBufferStatusByParameterList.js \
          ../pkgscript/dspJobCosting.js \
          ../pkgscript/dspLaborVarianceByBOOItem.js
          ../pkgscript/dspLaborVarianceByItem.js \
          ../pkgscript/dspLaborVarianceByWorkCenter.js \
          ../pkgscript/dspLaborVarianceByWorkOrder.js \
          ../pkgscript/dspMPSDetail.js \
          ../pkgscript/dspMRPException.js \
          ../pkgscript/dspOperationsByWorkCenter.js \
          ../pkgscript/dspPlannedRevenueExpensesByPlannerCode.js \
          ../pkgscript/dspPoItemsByBufferStatus.js \
          ../pkgscript/dspRoughCutByWorkCenter.js \
          ../pkgscript/dspSequencedBOM.js \
          ../pkgscript/dspSingleLevelWhereUsed.js \
          ../pkgscript/dspStandardOperationsByWorkCenter.js \
          ../pkgscript/dspTimePhasedAvailableCapacityByWorkCenter.js \
          ../pkgscript/dspTimePhasedCapacityByWorkCenter.js \
          ../pkgscript/dspTimePhasedDemandByPlannerCode.js \
          ../pkgscript/dspTimePhasedLoadByWorkCenter.js \
          ../pkgscript/dspTimePhasedPlannedREByPlannerCode.js \
          ../pkgscript/dspTimePhasedProductionByItem.js \
          ../pkgscript/dspTimePhasedProductionByPlannerCode.js \
          ../pkgscript/dspTimePhasedRoughCutByWorkCenter.js \
          ../pkgscript/dspUndefinedManufacturedItems.js \
          ../pkgscript/dspWoBufferStatusByParameterList.js \
          ../pkgscript/dspWoEffortByUser.js \
          ../pkgscript/dspWoEffortByWorkOrder.js \
          ../pkgscript/dspWoOperationBufrStsByWorkCenter.js \
          ../pkgscript/dspWoOperationsByWorkCenter.js \
          ../pkgscript/dspWoOperationsByWorkOrder.js \
          ../pkgscript/dspWoSchedule.js \
          ../pkgscript/employees.js     \
          ../pkgscript/initMenu.js \
          ../pkgscript/item.js \
          ../pkgscript/itemAvailabilityWorkbench.js \
          ../pkgscript/itemSite.js \
          ../pkgscript/items.js \
          ../pkgscript/laborRate.js \
          ../pkgscript/laborRates.js \
          ../pkgscript/ltanalysis.js \
          ../pkgscript/operationType.js \
          ../pkgscript/operationTypes.js        \
          ../pkgscript/plannedSchedule.js \
          ../pkgscript/plannedScheduleItem.js \
          ../pkgscript/plannedSchedules.js \
          ../pkgscript/plannerCode.js \
          ../pkgscript/postMiscProduction.js \
          ../pkgscript/postOperations.js \
          ../pkgscript/postProduction.js \
          ../pkgscript/printProductionEntrySheet.js \
          ../pkgscript/printWoRouting.js \
          ../pkgscript/printWoTraveler.js \
          ../pkgscript/purchaseOrderItem.js \
          ../pkgscript/rescheduleWo.js \
          ../pkgscript/returnAuthorizationItem.js \
          ../pkgscript/runMPSByPlannerCode.js \
          ../pkgscript/runMRPException.js \
          ../pkgscript/salesOrderItem.js \
          ../pkgscript/setup.js \
          ../pkgscript/shift.js \
          ../pkgscript/shifts.js \
          ../pkgscript/standardOperation.js \
          ../pkgscript/standardOperations.js \
          ../pkgscript/transferOrderItem.js \
          ../pkgscript/user.js \
          ../pkgscript/whseCalendar.js \
          ../pkgscript/whseCalendars.js \
          ../pkgscript/whseWeek.js \
          ../pkgscript/woMaterialItem.js \
          ../pkgscript/woOperation.js \
          ../pkgscript/woTimeClock.js \
          ../pkgscript/wooItemList.js \
          ../pkgscript/workCenter.js \
          ../pkgscript/workCenters.js \
          ../pkgscript/workOrder.js \
          ../pkgscript/workOrderOperations.js \
          ../pkgscript/wotc.js \
          ../pkgscript/xtmfgErrors.js \


TRANSLATIONS += xtmfg.base.ts   \
                xtmfg.ar_eg.ts  \
                xtmfg.bg.ts     \
                xtmfg.cn.ts     \
                xtmfg.cs.ts     \
                xtmfg.de.ts     \
                xtmfg.de_at.ts  \
                xtmfg.de_ch.ts  \
                xtmfg.en_ca.ts  \
                xtmfg.es.ts     \
                xtmfg.es_ar.ts  \
                xtmfg.es_mx.ts  \
                xtmfg.et_ee.ts  \
                xtmfg.fr.ts     \
                xtmfg.fr_ca.ts  \
                xtmfg.hr.ts     \
                xtmfg.it.ts     \
                xtmfg.jp.ts     \
                xtmfg.nl.ts     \
                xtmfg.no.ts     \
                xtmfg.pl.ts     \
                xtmfg.pt.ts     \
                xtmfg.pt_br.ts  \
                xtmfg.ru.ts     \
                xtmfg.sk.ts     \
                xtmfg.tr.ts     \
                xtmfg.ua.ts     \
                xtmfg.zh_hk.ts  \
                xtmfg.zh_tw.ts
