{
  "name": "manufacturing_foundation_frozen",
  "version": "1.8.1",
  "comment": "Manufacturing foundation",
  "loadOrder": 2000,
  "databaseScripts": [
    "frozen/create_xtmfg_schema.sql",
    "frozen/tables/bbomitem.sql",
    "frozen/tables/wrkcnt.sql",
    "frozen/tables/boohead.sql",
    "frozen/tables/booitem.sql",
    "frozen/tables/booimage.sql",
    "frozen/tables/brddist.sql",
    "frozen/tables/brdvar.sql",
    "frozen/tables/bufrsts.sql",
    "frozen/tables/itemsitecap.sql",
    "frozen/tables/lbrrate.sql",
    "frozen/tables/lt_report.sql",
    "frozen/tables/mrpexcp.sql",
    "frozen/tables/ovrhead.sql",
    "frozen/tables/planoper.sql",
    "frozen/tables/pschhead.sql",
    "frozen/tables/pschitem.sql",
    "frozen/tables/stdopn.sql",
    "frozen/tables/tashift.sql",
    "frozen/tables/wooper.sql",
    "frozen/tables/wooperpost.sql",
    "frozen/tables/woopervar.sql",
    "frozen/tables/wotc.sql",
    "frozen/tables/tatc.sql",
    "frozen/tables/whsecal.sql",
    "frozen/tables/whsewk.sql",
    "frozen/misc/setup_shifts.sql",
    "frozen/indexes/wotc.sql",
    "frozen/priv.sql"
  ]
}
