insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'public',
  'wo',
  'WorkOrder',
  'wo.obj_uuid',
  'wo.obj_uuid::text',
  'acttype_code',
  'formatwonumber(wo_id)',
  'wo_status != ''C''',
  'wo_status',
  'null',
  'item_descrip1',
  'wo_username',
  'wo_username',
  'wo_startdate',
  'wo_duedate',
  'null',
  'null',
  'null',
  'join itemsite on itemsite_id=wo_itemsite_id join item on itemsite_item_id=item_id'
);

insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_action,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'xt',
  'wowf',
  'WorkOrderWorkflow',
  'wowf.obj_uuid',
  'wo.obj_uuid::text',
  'acttype_code',
  'wf_name',
  'wf_status = ''I''',
  'wf_status',
  'wf_priority_id',
  'wf_description',
  'wf_owner_username',
  'wf_assigned_username',
  'wf_start_date',
  'wf_due_date',
  'wf_assigned_date',
  'wf_completed_date',
  'wf_type',
  'wo.obj_uuid::uuid',
  'join wo on wo.obj_uuid=wf_parent_uuid'
);
