{
  "name": "commercialcore_foundation",
  "version": "",
  "comment": "Commercial Core foundation",
  "loadOrder": 47,
  "defaultSchema": "xtcore",
  "databaseScripts": [
    "update_version.sql",
    "xtcore/create_xtcore_schema.sql",
    "xtcore/tables/obj.sql",
    "xtcore/add_uuid.sql",
    "xtcore/tables/wf.sql",
    "xtcore/tables/wfsrc.sql",
    "xtcore/tables/wftype.sql",
    "xtcore/tables/printer.sql",
    "xtcore/privs.sql",
    "public/tables/source.sql",
    "xtcore/functions/co_schedule_date.sql",
    "xtcore/functions/po_schedule_date.sql",
    "xtcore/tables/pkgscript/_obsolete.sql",
    "xtcore/tables/pkgscript/itemGroup.js",
    "xtcore/tables/pkgscript/ParameterGroupUtils.js",
    "xtcore/tables/pkgscript/xtCore.js",
    "xtcore/tables/pkgscript/xtCoreErrors.js",
    "xtcore/tables/emlprofile.sql",
    "xtcore/tables/coheadwf.sql",
    "xtcore/functions/createwf.sql",
    "xtcore/trigger_functions/createwf_triggers.sql",
    "xtcore/trigger_functions/workflow_update_successors.sql",
    "xtcore/trigger_functions/recv_item_did_change.sql",
    "xtcore/trigger_functions/ship_head_did_change.sql",
    "xtcore/trigger_functions/ship_item_did_change.sql",
    "xtcore/tables/potypewf.sql",
    "xtcore/tables/powf.sql",
    "xtcore/tables/prjtypewf.sql",
    "xtcore/tables/prjwf.sql",
    "xtcore/tables/saletypewf.sql",
    "xtcore/tables/sitetypewf.sql",
    "xtcore/views/ordhead.sql",
    "xtcore/views/orditem.sql",
    "xtcore/acttype.sql",
    "xtcore/pkgmetasql/WorkflowActivities-detail.mql",
    "xtcore/pkgmetasql/WorkflowList-detail.mql",
    "xtcore/patches/remove_databaseinformation_script.sql",
    "xtcore/pkgscript/initMenu.js",
    "xtcore/pkgscript/setup.js",
    "xtcore/pkgscript/configureWF.js",
    "xtcore/pkgscript/initMenu.js",
    "xtcore/pkgscript/setup.js",
    "xtcore/pkgscript/printer.js",
    "xtcore/pkgscript/printers.js",
    "xtcore/pkgscript/sharedwf.js",
    "xtcore/pkgscript/Workflow.js",
    "xtcore/pkgscript/WorkflowActivities.js",
    "xtcore/pkgscript/WorkflowActivity.js",
    "xtcore/pkgscript/WorkflowItem.js",
    "xtcore/pkgscript/workflowProfile.js",
    "xtcore/pkgscript/workflowProfiles.js",
    "xtcore/functions/copychars.sql",
    "xtcore/tables/wf_parentinfo.sql",
    "xtcore/tables/recv.sql",
    "xtcore/tables/shiphead.sql",
    "xtcore/tables/shipitem.sql",
    "xtcore/functions/workflow_inheritsource.sql",
    "xtcore/functions/workflow_notify.sql",
    "xtcore/trigger_functions/updatewf_triggers.sql",
    "xtcore/pkguiform/configureWF.ui",
    "xtcore/pkguiform/printer.ui",
    "xtcore/pkguiform/printers.ui",
    "xtcore/pkguiform/Workflow.ui",
    "xtcore/pkguiform/WorkflowActivity.ui",
    "xtcore/pkguiform/WorkflowItem.ui",
    "xtcore/pkguiform/workflowProfile.ui",
    "xtcore/pkguiform/workflowProfiles.ui"
  ]
}

