delete from xt.acttype where acttype_code = 'QualityTest';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'xt',
  'qthead',
  'QualityTest',
  'qthead.obj_uuid',
  'qthead.obj_uuid::text',
  'acttype_code',
  'qthead_number',
  'qthead_status = ''O''',
  'qthead_status',
  'null',
  'item_descrip1',
  'null',
  'null',
  'qthead_start_date',
  'qthead_completed_date',
  'null',
  'null',
  'null',
  'join item on item_id=qthead_item_id'
);


delete from xt.acttype where acttype_code = 'QualityTestWorkflow';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_action,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'xt',
  'qualitytestwf',
  'QualityTestWorkflow',
  'qualitytestwf.obj_uuid',
  'qthead.obj_uuid::text',
  'acttype_code',
  'wf_name',
  'wf_status = ''I''',
  'wf_status',
  'wf_priority_id',
  'wf_description',
  'wf_owner_username',
  'wf_assigned_username',
  'wf_start_date',
  'wf_due_date',
  'wf_assigned_date',
  'wf_completed_date',
  'wf_type',
  'qthead.obj_uuid::uuid',
  'join xt.qthead on xt.qthead.obj_uuid=wf_parent_uuid'
);

